# Generated by Django 6.0.4 on 2026-04-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('place_id', models.CharField(blank=True, max_length=200)),
                ('google_maps_url', models.URLField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horario', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Bibliotecas',
                'ordering': ['nombre'],
            },
        ),
    ]
